# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bilinear_admm3_cpp <- function(Ycube, Acube, w, C, lambda, U, V, Qbar, include_diag = TRUE, rho = 1.0, eta = 1.0, gamma_par = 1e-6, maxit = 100L, tol = 1e-3, snap_to_Z_every = 1L) {
    .Call('_SLACC_bilinear_admm3_cpp', PACKAGE = 'SLACC', Ycube, Acube, w, C, lambda, U, V, Qbar, include_diag, rho, eta, gamma_par, maxit, tol, snap_to_Z_every)
}

